'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { goals, levels, type Preferences } from '@/lib/learning';
import { useLearning } from './app-shell';
import { Icon, Portrait } from './ui';
export function PreferencesForm({ initial, settings = false }: { initial: Preferences; settings?: boolean }) {
  const [p, setP] = useState(initial); const [saved, setSaved] = useState(false); const { update } = useLearning(); const router = useRouter();
  function change(value: Partial<Preferences>) { setP({ ...p, ...value }); setSaved(false); }
  return <form className="preferences-form" onSubmit={e => { e.preventDefault(); update(d => ({ ...d, preferences: p, onboarded: true })); if (settings) setSaved(true); else router.push('/painel'); }}><fieldset><legend>Com quem você quer conversar?</legend><p className="field-description">Dois jeitos de receber você. O mesmo cuidado ao ensinar.</p><div className="tutor-options">{(['Emma', 'Ethan'] as const).map(tutor => <label key={tutor} className={`tutor-option ${p.tutor === tutor ? 'selected' : ''}`}><input type="radio" name="tutor" value={tutor} checked={p.tutor === tutor} onChange={() => change({ tutor })}/><Portrait tutor={tutor}/><span className="tutor-option-copy"><strong>{tutor}<span className="pill">Tutor com IA</span></strong><span>{tutor === 'Emma' ? '“Vamos encontrar as palavras, no seu ritmo.”' : '“Vamos levar seu inglês para a vida real.”'}</span><small>Voz americana · Personagem fictício</small></span><span className="selection-check"><Icon name="check" size={16}/></span></label>)}</div></fieldset><fieldset><legend>Qual é seu ponto de partida?</legend><div className="level-options">{levels.map((level, i) => <label key={level} className={`choice ${p.level === level ? 'selected' : ''}`}><input type="radio" name="level" value={level} checked={p.level === level} onChange={() => change({ level })}/><span className="level-bars" aria-hidden="true">{[0, 1, 2].map(n => <i key={n} className={n <= i ? 'lit' : ''}/>)}</span><strong>{level}</strong><span>{['Quero começar do básico.', 'Já consigo formar frases.', 'Quero conversar com fluidez.'][i]}</span></label>)}</div></fieldset><fieldset><legend>Onde você quer usar seu inglês?</legend><div className="goal-options">{goals.map(goal => <label key={goal} className={`goal-choice ${p.goal === goal ? 'selected' : ''}`}><input type="radio" name="goal" checked={p.goal === goal} onChange={() => change({ goal })}/>{goal}</label>)}</div></fieldset>{settings && <fieldset><legend>Deixe a aula do seu jeito</legend><label className="toggle-row"><span><strong>Áudio do tutor</strong><small>Reproduzir respostas automaticamente. Voz gerada por IA.</small></span><input type="checkbox" checked={p.audio} onChange={e => change({ audio: e.target.checked })}/></label><label className="toggle-row"><span><strong>Legendas em português</strong><small>Mostrar a tradução junto da conversa.</small></span><input type="checkbox" checked={p.captions} onChange={e => change({ captions: e.target.checked })}/></label></fieldset>}<div className="form-footer"><p>Você pode mudar tudo isso depois.<br/>Seu progresso continua com você.</p><button className="button primary" type="submit">{settings ? 'Salvar preferências' : 'Entrar no meu espaço'}<Icon name={settings ? 'check' : 'arrow'}/></button></div>{saved && <p className="success" role="status">Preferências atualizadas.</p>}</form>;
}
